/**
 * 共享的 Vant 组件 Stubs
 * 在组件测试中使用，避免依赖 Vant 的 DOM 渲染。
 * 注意：所有 stub 模板必须通过 $attrs.class 转发父组件的 :class 绑定。
 */
export const vanStubs: Record<string, any> = {
  // ===== 导航类 =====
  VanNavBar: {
    name: 'VanNavBar',
    template:
      '<div :class="[\'van-nav-bar\', $attrs.class]"><slot name="left" /><slot name="title" /><slot name="right" /></div>',
    props: [
      'title',
      'fixed',
      'safeAreaInsetTop',
      'leftArrow',
      'leftText',
      'rightText',
      'border',
      'placeholder',
      'zIndex',
    ],
  },
  VanTab: {
    name: 'VanTab',
    template: '<div :class="[\'van-tab\', $attrs.class]"><slot /></div>',
    props: ['title', 'disabled', 'badge', 'dot', 'name', 'url', 'to'],
  },
  VanTabs: {
    name: 'VanTabs',
    template: '<div :class="[\'van-tabs\', $attrs.class]"><slot /></div>',
    props: [
      'active',
      'type',
      'color',
      'border',
      'sticky',
      'shrink',
      'duration',
      'animated',
      'ellipsis',
      'swipeable',
      'scrollspy',
      'offsetTop',
      'background',
      'lazyRender',
      'showHeader',
      'lineWidth',
      'lineHeight',
    ],
  },
  VanStep: {
    name: 'VanStep',
    template:
      '<div :class="[\'van-step\', $attrs.class]"><slot /><slot name="active-icon" /><slot name="inactive-icon" /></div>',
  },
  VanSteps: {
    name: 'VanSteps',
    template: '<div :class="[\'van-steps\', $attrs.class]"><slot /></div>',
    props: ['active', 'direction', 'activeIcon', 'inactiveIcon'],
  },
  VanBackTop: {
    name: 'VanBackTop',
    template: '<div :class="[\'van-back-top\', $attrs.class]"><slot /></div>',
    props: ['visible', 'target', 'offset', 'bottom', 'right', 'zIndex'],
  },
  VanTabbar: {
    name: 'VanTabbar',
    template: '<div :class="[\'van-tabbar\', $attrs.class]"><slot /></div>',
    props: [
      'modelValue',
      'route',
      'placeholder',
      'safeAreaInsetBottom',
      'fixed',
      'border',
      'zIndex',
      'activeColor',
      'inactiveColor',
    ],
  },
  VanTabbarItem: {
    name: 'VanTabbarItem',
    template: '<div :class="[\'van-tabbar-item\', $attrs.class]"><slot /><slot name="icon" /></div>',
    props: ['name', 'to', 'badge', 'dot', 'icon'],
  },

  // ===== 展示类 =====
  VanCell: {
    name: 'VanCell',
    template:
      '<div :class="[\'van-cell\', $attrs.class]"><slot /><slot name="title" /><slot name="label" /><slot name="value" /><slot name="icon" /></div>',
    props: ['title', 'value', 'label', 'icon', 'size', 'is-link', 'required', 'border', 'center'],
  },
  VanCellGroup: {
    name: 'VanCellGroup',
    template: '<div :class="[\'van-cell-group\', $attrs.class]"><slot /></div>',
    props: ['title', 'border'],
  },
  VanCard: {
    name: 'VanCard',
    template:
      '<div :class="[\'van-card\', $attrs.class]"><slot /><slot name="thumb" /><slot name="title" /><slot name="tags" /><slot name="price" /><slot name="num" /><slot name="origin-price" /><slot name="bottom" /></div>',
    props: ['thumb', 'title', 'desc', 'tag', 'price', 'num', 'originPrice', 'centered', 'currency', 'lazyLoad'],
  },
  VanTag: {
    name: 'VanTag',
    template: '<span :class="[\'van-tag\', $attrs.class]"><slot /></span>',
    props: ['type', 'size', 'color', 'plain', 'round', 'mark', 'textColor', 'closeable'],
  },
  VanBadge: {
    name: 'VanBadge',
    template: '<div :class="[\'van-badge\', $attrs.class]"><slot /><slot name="content" /></div>',
    props: ['dot', 'content', 'max', 'color', 'position', 'tag', 'offset', 'showZero'],
  },
  VanCollapse: {
    name: 'VanCollapse',
    template: '<div :class="[\'van-collapse\', $attrs.class]"><slot /></div>',
    props: ['modelValue', 'accordion', 'border'],
  },
  VanCollapseItem: {
    name: 'VanCollapseItem',
    template:
      '<div :class="[\'van-collapse-item\', $attrs.class]"><slot /><slot name="title" /><slot name="value" /><slot name="icon" /><slot name="right-icon" /></div>',
    props: ['name', 'title', 'value', 'icon', 'label', 'disabled', 'border', 'isLink', 'clickable'],
  },
  VanDivider: {
    name: 'VanDivider',
    template: '<div :class="[\'van-divider\', $attrs.class]"><slot /></div>',
    props: ['dashed', 'hairline', 'contentPosition'],
  },
  VanImage: {
    name: 'VanImage',
    template: '<div :class="[\'van-image\', $attrs.class]"><slot /><slot name="loading" /><slot name="error" /></div>',
    props: ['src', 'fit', 'alt', 'width', 'height', 'radius', 'round', 'lazyLoad', 'showError', 'showLoading'],
  },
  VanLoading: {
    name: 'VanLoading',
    template: '<div :class="[\'van-loading\', $attrs.class]"><slot /></div>',
    props: ['type', 'color', 'size', 'text-size', 'vertical', 'text-color'],
  },
  VanEmpty: {
    name: 'VanEmpty',
    template:
      '<div :class="[\'van-empty\', $attrs.class]"><slot /><slot name="image" /><slot name="description" /></div>',
    props: ['image', 'imageSize', 'description'],
  },
  VanSkeleton: {
    name: 'VanSkeleton',
    template: '<div :class="[\'van-skeleton\', $attrs.class]"><slot /></div>',
    props: ['row', 'rowWidth', 'title', 'avatar', 'avatarSize', 'round', 'loading', 'animate'],
  },
  VanSkeletonImage: {
    name: 'VanSkeletonImage',
    template: '<div :class="[\'van-skeleton-image\', $attrs.class]" />',
    props: ['row', 'rowWidth', 'title', 'round', 'loading', 'animate'],
  },
  VanSkeletonParagraph: {
    name: 'VanSkeletonParagraph',
    template: '<div :class="[\'van-skeleton-paragraph\', $attrs.class]" />',
    props: ['row', 'rowWidth', 'round', 'loading', 'animate'],
  },

  // ===== 反馈类 =====
  VanToast: {
    name: 'VanToast',
    template: '<div :class="[\'van-toast\', $attrs.class]"><slot name="message" /></div>',
    props: [
      'show',
      'type',
      'position',
      'message',
      'icon',
      'duration',
      'mask',
      'forbidClick',
      'closeOnClick',
      'transition',
      'teleport',
    ],
  },
  VanDialog: {
    name: 'VanDialog',
    template: '<div :class="[\'van-dialog\', $attrs.class]"><slot /><slot name="title" /><slot name="footer" /></div>',
    props: [
      'show',
      'title',
      'message',
      'messageAlign',
      'confirmButtonText',
      'cancelButtonText',
      'confirmButtonColor',
      'cancelButtonColor',
      'showConfirmButton',
      'showCancelButton',
      'closeOnPopstate',
    ],
  },
  VanPopup: {
    name: 'VanPopup',
    template: '<div :class="[\'van-popup\', $attrs.class]"><slot /></div>',
    props: [
      'show',
      'position',
      'overlay',
      'closeable',
      'closeIcon',
      'closeIconPosition',
      'round',
      'duration',
      'lockScroll',
      'safeAreaInsetBottom',
      'safeAreaInsetTop',
      'teleport',
    ],
  },
  VanActionSheet: {
    name: 'VanActionSheet',
    template:
      '<div :class="[\'van-action-sheet\', $attrs.class]"><slot /><slot name="description" /><slot name="header" /></div>',
    props: [
      'show',
      'actions',
      'title',
      'description',
      'cancelText',
      'closeOnClickAction',
      'closeable',
      'round',
      'duration',
    ],
  },
  VanImagePreview: {
    name: 'VanImagePreview',
    template: '<div :class="[\'van-image-preview\', $attrs.class]"><slot /></div>',
    props: [
      'show',
      'images',
      'loop',
      'minZoom',
      'maxZoom',
      'overlay',
      'vertical',
      'closeable',
      'closeIcon',
      'startPosition',
    ],
  },

  // ===== 表单类 =====
  VanButton: {
    name: 'VanButton',
    template: '<button :class="[\'van-button\', $attrs.class]"><slot /></button>',
    props: [
      'type',
      'size',
      'color',
      'plain',
      'block',
      'round',
      'disabled',
      'loading',
      'native-type',
      'icon',
      'iconPosition',
    ],
  },
  VanField: {
    name: 'VanField',
    template:
      '<div :class="[\'van-field\', $attrs.class]"><slot name="left-icon" /><slot name="right-icon" /><slot name="input" /><slot name="button" /><slot name="extra" /></div>',
    props: [
      'modelValue',
      'label',
      'placeholder',
      'type',
      'name',
      'clearable',
      'disabled',
      'readonly',
      'maxlength',
      'required',
      'border',
      'isLink',
      'error',
      'errorMessage',
      'labelAlign',
      'inputAlign',
      'labelWidth',
      'colon',
      'showWordLimit',
      'rows',
      'autosize',
    ],
  },
  VanForm: {
    name: 'VanForm',
    template: '<div :class="[\'van-form\', $attrs.class]"><slot /></div>',
    props: [
      'modelValue',
      'scrollToError',
      'validationTrigger',
      'showErrorMessage',
      'showError',
      'labelWidth',
      'labelAlign',
      'inputAlign',
      'errorMessageAlign',
    ],
  },
  VanPicker: {
    name: 'VanPicker',
    template:
      '<div :class="[\'van-picker\', $attrs.class]"><slot name="title" /><slot name="toolbar" /><slot name="option" /><slot name="columns-top" /><slot name="columns-bottom" /><slot name="empty" /></div>',
    props: ['modelValue', 'columns', 'title', 'loading', 'readonly'],
  },
  VanTimePicker: {
    name: 'VanTimePicker',
    template: '<div :class="[\'van-time-picker\', $attrs.class]" />',
    props: [
      'modelValue',
      'columnsType',
      'minHour',
      'maxHour',
      'minMinute',
      'maxMinute',
      'minSecond',
      'maxSecond',
      'title',
      'loading',
      'readonly',
    ],
  },
  VanArea: {
    name: 'VanArea',
    template: '<div :class="[\'van-area\', $attrs.class]" />',
    props: ['modelValue', 'areaList', 'columnsNum', 'columnsPlaceholder', 'title', 'loading', 'readonly'],
  },
  VanCalendar: {
    name: 'VanCalendar',
    template: '<div :class="[\'van-calendar\', $attrs.class]"><slot name="title" /><slot name="footer" /></div>',
    props: [
      'show',
      'type',
      'title',
      'color',
      'minDate',
      'maxDate',
      'defaultDate',
      'rowHeight',
      'formatter',
      'poppable',
      'round',
      'closeable',
      'showConfirm',
      'showSubtitle',
    ],
  },
  VanSearch: {
    name: 'VanSearch',
    template:
      '<div :class="[\'van-search\', $attrs.class]"><slot name="left-icon" /><slot name="right-icon" /><slot name="action" /><slot name="label" /></div>',
    props: [
      'modelValue',
      'label',
      'placeholder',
      'shape',
      'clearable',
      'disabled',
      'readonly',
      'maxlength',
      'showAction',
      'actionText',
      'leftIcon',
      'rightIcon',
    ],
  },
  VanSwitch: {
    name: 'VanSwitch',
    template: '<div :class="[\'van-switch\', $attrs.class]" />',
    props: ['modelValue', 'loading', 'disabled', 'size', 'activeColor', 'inactiveColor'],
  },
  VanStepper: {
    name: 'VanStepper',
    template: '<div :class="[\'van-stepper\', $attrs.class]" />',
    props: ['modelValue', 'min', 'max', 'step', 'integer', 'disabled', 'inputWidth', 'buttonSize'],
  },
  VanCheckbox: {
    name: 'VanCheckbox',
    template: '<div :class="[\'van-checkbox\', $attrs.class]"><slot /></div>',
    props: ['modelValue', 'name', 'disabled', 'shape', 'iconSize', 'checkedColor', 'labelPosition', 'labelDisabled'],
  },
  VanCheckboxGroup: {
    name: 'VanCheckboxGroup',
    template: '<div :class="[\'van-checkbox-group\', $attrs.class]"><slot /></div>',
    props: ['modelValue', 'max', 'disabled', 'direction', 'iconSize', 'checkedColor'],
  },
  VanRadio: {
    name: 'VanRadio',
    template: '<div :class="[\'van-radio\', $attrs.class]"><slot /></div>',
    props: ['modelValue', 'name', 'disabled', 'shape', 'iconSize', 'checkedColor', 'labelPosition', 'labelDisabled'],
  },
  VanRadioGroup: {
    name: 'VanRadioGroup',
    template: '<div :class="[\'van-radio-group\', $attrs.class]"><slot /></div>',
    props: ['modelValue', 'disabled', 'direction', 'iconSize', 'checkedColor'],
  },
  VanRate: {
    name: 'VanRate',
    template: '<div :class="[\'van-rate\', $attrs.class]" />',
    props: [
      'modelValue',
      'count',
      'size',
      'color',
      'voidColor',
      'icon',
      'voidIcon',
      'allowHalf',
      'readonly',
      'disabled',
    ],
  },
  VanSlider: {
    name: 'VanSlider',
    template: '<div :class="[\'van-slider\', $attrs.class]" />',
    props: ['modelValue', 'min', 'max', 'step', 'range', 'disabled', 'vertical', 'barHeight'],
  },
  VanUploader: {
    name: 'VanUploader',
    template: '<div :class="[\'van-uploader\', $attrs.class]"><slot /></div>',
    props: ['modelValue', 'accept', 'multiple', 'disabled', 'maxCount', 'maxSize', 'previewCoverIcon'],
  },

  // ===== 基础类 =====
  VanIcon: {
    name: 'VanIcon',
    template: '<i :class="[\'van-icon\', $attrs.class]"><slot /></i>',
    props: ['name', 'dot', 'badge', 'size', 'color', 'classPrefix'],
  },

  // ===== 新增组件 =====
  VanCountDown: {
    name: 'VanCountDown',
    template: '<div :class="[\'van-count-down\', $attrs.class]" />',
    props: ['time', 'format', 'autoStart', 'millisecond'],
  },
  VanPullRefresh: {
    name: 'VanPullRefresh',
    template:
      '<div :class="[\'van-pull-refresh\', $attrs.class]"><slot /><slot name="pulling" /><slot name="loosing" /><slot name="loading" /></div>',
    props: [
      'modelValue',
      'loading',
      'pullingText',
      'loosingText',
      'loadingText',
      'successText',
      'successDuration',
      'animationDuration',
      'headHeight',
      'disabled',
    ],
  },
  VanList: {
    name: 'VanList',
    template:
      '<div :class="[\'van-list\', $attrs.class]"><slot /><slot name="loading" /><slot name="finished" /><slot name="error" /></div>',
    props: [
      'modelValue',
      'loading',
      'finished',
      'error',
      'offset',
      'loadingText',
      'finishedText',
      'errorText',
      'immediateCheck',
      'direction',
    ],
  },
  VanIndexBar: {
    name: 'VanIndexBar',
    template: '<div :class="[\'van-index-bar\', $attrs.class]"><slot /></div>',
    props: ['modelValue', 'sticky', 'stickyOffset', 'zIndex', 'highlightColor', 'stickyColor'],
  },
  VanIndexAnchor: {
    name: 'VanIndexAnchor',
    template: '<div :class="[\'van-index-anchor\', $attrs.class]"><slot /></div>',
    props: ['index'],
  },
  VanSidebar: {
    name: 'VanSidebar',
    template: '<div :class="[\'van-sidebar\', $attrs.class]"><slot /></div>',
    props: ['modelValue'],
  },
  VanSidebarItem: {
    name: 'VanSidebarItem',
    template: '<div :class="[\'van-sidebar-item\', $attrs.class]" />',
    props: ['title', 'badge', 'dot', 'disabled'],
  },
  VanNumberKeyboard: {
    name: 'VanNumberKeyboard',
    template: '<div :class="[\'van-number-keyboard\', $attrs.class]"><slot name="title" /><slot name="extra" /></div>',
    props: [
      'show',
      'modelValue',
      'title',
      'transition',
      'zIndex',
      'maxlength',
      'deleteButtonText',
      'closeButtonText',
      'showDeleteKey',
      'randomOrder',
      'safeAreaInsetBottom',
    ],
  },
  VanPasswordInput: {
    name: 'VanPasswordInput',
    template: '<div :class="[\'van-password-input\', $attrs.class]" />',
    props: ['modelValue', 'value', 'length', 'gutter', 'mask', 'focused', 'info', 'errorInfo'],
  },
  VanWatermark: {
    name: 'VanWatermark',
    template: '<div :class="[\'van-watermark\', $attrs.class]" />',
    props: [
      'width',
      'height',
      'content',
      'image',
      'rotate',
      'zIndex',
      'opacity',
      'fullPage',
      'textColor',
      'gapX',
      'gapY',
    ],
  },
  VanFloatingPanel: {
    name: 'VanFloatingPanel',
    template: '<div :class="[\'van-floating-panel\', $attrs.class]"><slot /></div>',
    props: [
      'height',
      'anchors',
      'duration',
      'magnetic',
      'draggable',
      'contentDraggable',
      'lockScroll',
      'safeAreaInsetBottom',
    ],
  },
};
